GET http://localhost:3000/south-coast-crawlers/accounts/email@emailsite.co.uk/tobehashed

###

GET http://localhost:3000/south-coast-crawlers/accounts/60a7b83cd0788cb640e21870

###

POST http://localhost:3000/south-coast-crawlers/accounts
Content-Type: application/json

{
    "username": "example2",
    "name": "example name2",
    "email": "test2@emailsite.co.uk",
    "password": "test2a"
}

###
60ab60cf4d488c3742cbad5b
test@emailsite.co.uk
5d197c3a69
DELETE http://localhost:3000/south-coast-crawlers/accounts


--------------------------------------------------------------------------------------
###

GET http://localhost:3000/south-coast-crawlers/events

###

GET http://localhost:3000/south-coast-crawlers/events/60a7b83cd0788cb640e21870

###

POST http://localhost:3000/south-coast-crawlers/events
Content-Type: application/json

{
    "ownerID": "60a7ea643ea48fea2ab84773",
    "eventName": "gooasdifj8uashet",
    "ruleset": "rcsccgb",
    "startDate": "2021-06-12"
}

###

DELETE http://localhost:3000/south-coast-crawlers/events/60a7ea643ea48fea2ab84773/60a7ea8f3ea48fea2ab84776

